import { describe, it, expect, vi, beforeEach } from "vitest";

const mockFindUnique = vi.fn();

vi.mock("@/lib/prisma", () => ({
  requirePrisma: vi.fn(() => ({
    team: {
      findUnique: mockFindUnique,
    },
  })),
}));

import { createUniqueInviteCode, isValidInviteCodeFormat, generateInviteCode } from "./inviteCode";

describe("inviteCode", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  describe("createUniqueInviteCode", () => {
    it("generates a code of exactly 6 characters", async () => {
      mockFindUnique.mockResolvedValue(null);
      const code = await createUniqueInviteCode();
      expect(code).toHaveLength(6);
    });

    it("uses only valid charset characters (consonants + digits, no vowels)", async () => {
      mockFindUnique.mockResolvedValue(null);
      for (let i = 0; i < 20; i++) {
        const code = await createUniqueInviteCode();
        expect(isValidInviteCodeFormat(code)).toBe(true);
      }
    });

    it("generates uppercase characters only", async () => {
      mockFindUnique.mockResolvedValue(null);
      const code = await createUniqueInviteCode();
      expect(code).toBe(code.toUpperCase());
    });

    it("retries when code already exists in database", async () => {
      const mockTeam = { id: "1", inviteCode: "BCDFGH" } as never;
      mockFindUnique
        .mockResolvedValueOnce(mockTeam)     // 1st attempt: collision
        .mockResolvedValueOnce(null);         // 2nd attempt: unique
      const code = await createUniqueInviteCode();
      expect(code).toHaveLength(6);
      expect(mockFindUnique).toHaveBeenCalledTimes(2);
    });

    it("throws after max retries (3 consecutive collisions)", async () => {
      const mockTeam = { id: "1", inviteCode: "BCDFGH" } as never;
      mockFindUnique.mockResolvedValue(mockTeam);
      await expect(createUniqueInviteCode()).rejects.toThrow(
        "Failed to generate unique invite code after max retries"
      );
      expect(mockFindUnique).toHaveBeenCalledTimes(3);
    });

    it("checks uniqueness against the database", async () => {
      mockFindUnique.mockResolvedValue(null);
      const code = await createUniqueInviteCode();
      expect(mockFindUnique).toHaveBeenCalledWith({
        where: { inviteCode: code },
      });
    });

    it("produces varied codes (basic randomness check)", async () => {
      mockFindUnique.mockResolvedValue(null);
      const codes = new Set<string>();
      for (let i = 0; i < 10; i++) {
        codes.add(await createUniqueInviteCode());
      }
      // With crypto randomness, 10 codes should almost certainly be unique
      expect(codes.size).toBeGreaterThanOrEqual(8);
    });
  });

  describe("isValidInviteCodeFormat", () => {
    it("accepts a valid 6-char uppercase code", () => {
      expect(isValidInviteCodeFormat("BCD123")).toBe(true);
    });

    it("accepts lowercase input (auto-uppercases)", () => {
      expect(isValidInviteCodeFormat("bcd123")).toBe(true);
    });

    it("accepts mixed case input", () => {
      expect(isValidInviteCodeFormat("BcD1x3")).toBe(true);
    });

    it("rejects codes with vowels", () => {
      expect(isValidInviteCodeFormat("ABCDEF")).toBe(false);
      expect(isValidInviteCodeFormat("EBCD12")).toBe(false);
      expect(isValidInviteCodeFormat("BCD12I")).toBe(false);
      expect(isValidInviteCodeFormat("BCD1O2")).toBe(false);
      expect(isValidInviteCodeFormat("UBCD12")).toBe(false);
    });

    it("rejects codes shorter than 6 chars", () => {
      expect(isValidInviteCodeFormat("BCD12")).toBe(false);
      expect(isValidInviteCodeFormat("B")).toBe(false);
    });

    it("rejects codes longer than 6 chars", () => {
      expect(isValidInviteCodeFormat("BCD1234")).toBe(false);
    });

    it("rejects empty string", () => {
      expect(isValidInviteCodeFormat("")).toBe(false);
    });

    it("rejects special characters", () => {
      expect(isValidInviteCodeFormat("BCD!@#")).toBe(false);
      expect(isValidInviteCodeFormat("BCD 12")).toBe(false);
    });

    it("rejects non-string input", () => {
      expect(isValidInviteCodeFormat(null as unknown as string)).toBe(false);
      expect(isValidInviteCodeFormat(undefined as unknown as string)).toBe(false);
      expect(isValidInviteCodeFormat(123456 as unknown as string)).toBe(false);
    });

    it("validates codes generated by generateInviteCode", () => {
      for (let i = 0; i < 20; i++) {
        const code = generateInviteCode();
        expect(isValidInviteCodeFormat(code)).toBe(true);
      }
    });
  });
});
