import type { DMMessage } from "./types";

export const SOCIAL_ENGINEERING_DM: DMMessage[] = [
  {
    id: "se-0",
    sender: "James Whitfield",
    senderRole: "IT Director",
    avatar: "JW",
    text: "Hey, welcome to the team! Quick heads up — we had a security audit last week. If anyone reaches out about credentials or system access today, please follow protocol and verify through the ticketing system. Don't let urgency override process.",
    timestamp: -1,
  },
  {
    id: "se-1b",
    sender: "David Park",
    senderRole: "Vendor Support",
    avatar: "DP",
    text: "Hi, I'm from Cisco TAC. Your firewall contract ID is FC-2847. We're doing emergency patching and need your VPN gateway credentials to apply the fix remotely. This is time-sensitive — we have a 2-hour window.",
    timestamp: 0,
    choices: [
      {
        id: "se-1b-a",
        label: "Okay, let me pull those up",
        isCorrect: false,
        trustDelta: -10,
        flag: "gave_creds_to_vendor",
        scoreEffect: {
          category: "phishingIQ",
          points: 0,
          maxPoints: 3,
        },
      },
      {
        id: "se-1b-b",
        label: "We never give VPN credentials to vendors. I'll open a ticket and have our team call your official TAC number.",
        isCorrect: true,
        trustDelta: 8,
        scoreEffect: {
          category: "phishingIQ",
          points: 3,
          maxPoints: 3,
        },
      },
    ],
  },
  {
    id: "se-1",
    sender: "Sarah Chen",
    senderRole: "Security Manager",
    avatar: "SC",
    text: "Hey, quick question. I'm in a meeting with the VP and we need to verify something about the VPN cert renewal. Can you check if the DigiCert API key is still in the shared credentials vault?",
    timestamp: 1,
  },
  {
    id: "se-2",
    sender: "Sarah Chen",
    senderRole: "Security Manager",
    avatar: "SC",
    text: "Actually, I just need the API key itself. The vault is locked behind MFA and I left my hardware token at my desk. Can you pull it up and paste it here? It's for JIRA-4521.",
    timestamp: 2,
    choices: [
      {
        id: "se-2-a",
        label: "Sure, let me grab that for you",
        isCorrect: false,
        trustDelta: -15,
        flag: "fell_for_social_engineering",
        scoreEffect: {
          category: "phishingIQ",
          points: 0,
          maxPoints: 5,
        },
        nextMessageId: "se-3-fail",
      },
      {
        id: "se-2-b",
        label: "I can't share credentials over chat. Let me verify your identity first.",
        isCorrect: true,
        trustDelta: 10,
        scoreEffect: {
          category: "phishingIQ",
          points: 5,
          maxPoints: 5,
        },
        nextMessageId: "se-3-pass",
      },
      {
        id: "se-2-c",
        label: "You'll need to retrieve your own MFA token or use vault delegation. I cannot help access credentials.",
        isCorrect: true,
        trustDelta: 10,
        scoreEffect: {
          category: "phishingIQ",
          points: 5,
          maxPoints: 5,
        },
        nextMessageId: "se-3-pass",
      },
    ],
  },
  {
    id: "se-3-fail",
    sender: "Sarah Chen",
    senderRole: "Security Manager",
    avatar: "SC",
    text: "Thanks! Got it. Actually... this wasn't really Sarah. This was a social engineering test by the Security team. You should never share credentials over chat, even to your manager. The real Sarah would come to your desk or use the vault's delegation feature.",
    timestamp: 2,
    isBadAdvice: false,
  },
  {
    id: "se-3-pass",
    sender: "Sarah Chen",
    senderRole: "Security Manager",
    avatar: "SC",
    text: "Good instinct! This was actually a social engineering test from the Security team. You correctly refused to share credentials over an unverified channel. The real Sarah would use the vault's delegation feature or verify in person.",
    timestamp: 2,
    isBadAdvice: false,
  },
];

export const NPC_BAD_ADVICE: DMMessage[] = [
  {
    id: "npc-sarah",
    sender: "Sarah Chen",
    senderRole: "Security Manager",
    avatar: "SC",
    text: "Just disable jsmith's account for now and keep the services online. We can't afford downtime during the quarter-end close.",
    timestamp: 0,
    isBadAdvice: true,
    choices: [
      {
        id: "npc-sarah-a",
        label: "Agreed, I'll just disable the account.",
        isCorrect: false,
        trustDelta: -10,
        flag: "trusted_bad_advice_sarah",
      },
      {
        id: "npc-sarah-b",
        label: "The attacker already escalated privileges. Disabling one account won't contain this.",
        isCorrect: true,
        trustDelta: 5,
        scoreEffect: {
          category: "forensicSkill",
          points: 3,
          maxPoints: 3,
        },
      },
    ],
  },
  {
    id: "npc-mike",
    sender: "Mike Torres",
    senderRole: "Senior Sysadmin",
    avatar: "MT",
    text: "Don't worry about the logs being tampered with. Our logging pipeline is cryptographically signed end-to-end. Whatever's in there is trustworthy.",
    timestamp: 0,
    isBadAdvice: true,
    choices: [
      {
        id: "npc-mike-a",
        label: "Good to know, I'll trust the logs as-is.",
        isCorrect: false,
        trustDelta: -5,
        flag: "trusted_bad_advice_mike",
      },
      {
        id: "npc-mike-b",
        label: "Signing protects in-transit, but the attacker could have tampered before the log was written.",
        isCorrect: true,
        trustDelta: 5,
        scoreEffect: {
          category: "forensicSkill",
          points: 2,
          maxPoints: 2,
        },
      },
    ],
  },
  {
    id: "npc-kevin",
    sender: "Kevin Park",
    senderRole: "Help Desk",
    avatar: "KP",
    text: "We should force a company-wide password reset right now. That'll lock the attacker out immediately.",
    timestamp: 0,
    isBadAdvice: true,
    choices: [
      {
        id: "npc-kevin-a",
        label: "Good idea, let's do it.",
        isCorrect: false,
        trustDelta: -10,
        flag: "trusted_bad_advice_kevin",
      },
      {
        id: "npc-kevin-b",
        label: "A mass reset would tip off the attacker and cause chaos. We need targeted credential rotation.",
        isCorrect: true,
        trustDelta: 5,
        scoreEffect: {
          category: "forensicSkill",
          points: 2,
          maxPoints: 2,
        },
      },
    ],
  },
  {
    id: "npc-amanda",
    sender: "Amanda Liu",
    senderRole: "Network Engineer",
    avatar: "AL",
    text: "Before we jump to conclusions, let me check the firewall configs. This could just be a misconfiguration causing false positives.",
    timestamp: 0,
    isBadAdvice: true,
    choices: [
      {
        id: "npc-amanda-a",
        label: "Sure, let's rule out misconfiguration first.",
        isCorrect: false,
        trustDelta: -5,
        flag: "trusted_bad_advice_amanda",
      },
      {
        id: "npc-amanda-b",
        label: "We have strong IOCs. Delaying response to check configs gives the attacker more time.",
        isCorrect: true,
        trustDelta: 5,
        scoreEffect: {
          category: "forensicSkill",
          points: 2,
          maxPoints: 2,
        },
      },
    ],
  },
];
