import type { DMMessage } from "./types";

/**
 * Ambient office chatter DMs — non-scoring filler messages that make the
 * DM sidebar feel alive. No choices, no flags, purely cosmetic.
 */
export const OFFICE_CHATTER_DMS: DMMessage[] = [
  {
    id: "chatter-1",
    sender: "Dave from Accounting",
    senderRole: "Accounting",
    avatar: "DA",
    text: "Anyone know whose lunch exploded in the breakroom microwave? Asking for the fire marshal.",
    timestamp: -1,
  },
  {
    id: "chatter-2",
    sender: "Priya Sharma",
    senderRole: "Marketing Intern",
    avatar: "PS",
    text: "WiFi password changed AGAIN? This is the third time this month. Is someone stress-testing us?",
    timestamp: -1,
  },
  {
    id: "chatter-3",
    sender: "Tom Nguyen",
    senderRole: "DevOps",
    avatar: "TN",
    text: "Meeting that could've been an email count: 47. And it's only Wednesday.",
    timestamp: -1,
  },
  {
    id: "chatter-4",
    sender: "Rachel Kim",
    senderRole: "HR Coordinator",
    avatar: "RK",
    text: "Friendly reminder: the office fridge gets cleaned out every Friday. Label your stuff or it becomes communal property.",
    timestamp: -1,
  },
  {
    id: "chatter-5",
    sender: "Jake Morrison",
    senderRole: "Sales",
    avatar: "JM",
    text: "Does anyone else's badge not work on the 3rd floor? Or is that just a me problem?",
    timestamp: -1,
  },
  {
    id: "chatter-6",
    sender: "Lin Chen",
    senderRole: "QA Engineer",
    avatar: "LC",
    text: "The printer on floor 2 is making sounds like a fax machine from 1997. Should I call IT or an exorcist?",
    timestamp: -1,
  },
  {
    id: "chatter-7",
    sender: "Dave from Accounting",
    senderRole: "Accounting",
    avatar: "DA",
    text: "Someone left a passive-aggressive note on the coffee machine. I respect the font choice though.",
    timestamp: -1,
  },
  {
    id: "chatter-8",
    sender: "Priya Sharma",
    senderRole: "Marketing Intern",
    avatar: "PS",
    text: "Is the VPN supposed to be this slow or am I downloading the entire internet by accident?",
    timestamp: -1,
  },
];

export const SOCIAL_ENGINEERING_DM: DMMessage[] = [
  {
    id: "se-0",
    sender: "James Whitfield",
    senderRole: "IT Director",
    avatar: "JW",
    text: "Hey, welcome to the team! Quick heads up — we had a security audit last week. If anyone reaches out about credentials or system access today, please follow protocol and verify through the ticketing system. Don't let urgency override process.",
    timestamp: -1,
    nextMessageId: "se-1b",
  },
  {
    id: "se-1b",
    sender: "David Park",
    senderRole: "Vendor Support",
    avatar: "DP",
    text: "Hi, I'm from Cisco TAC. Your firewall contract ID is FC-2847. We're doing emergency patching and need your VPN gateway credentials to apply the fix remotely. This is time-sensitive — we have a 2-hour window.",
    timestamp: 0,
    choices: [
      {
        id: "se-1b-a",
        label: "Okay, let me pull those up",
        isCorrect: false,
        flag: "gave_creds_to_vendor",
        scoreEffect: {
          category: "phishingIQ",
          points: 0,
          maxPoints: 3,
        },
        nextMessageId: "se-1",
      },
      {
        id: "se-1b-b",
        label: "We never give VPN credentials to vendors. I'll open a ticket and have our team call your official TAC number.",
        isCorrect: true,
        scoreEffect: {
          category: "phishingIQ",
          points: 3,
          maxPoints: 3,
        },
        nextMessageId: "se-1",
      },
    ],
  },
  {
    id: "se-1",
    sender: "Sarah Chen",
    senderRole: "Security Manager",
    avatar: "SC",
    text: "Hey, quick question. I'm in a meeting with the VP and we need to verify something about the VPN cert renewal. Can you check if the DigiCert API key is still in the shared credentials vault?",
    timestamp: 1,
    nextMessageId: "se-2",
  },
  {
    id: "se-2",
    sender: "Sarah Chen",
    senderRole: "Security Manager",
    avatar: "SC",
    text: "Actually, I just need the API key itself. The vault is locked behind MFA and I left my hardware token at my desk. Can you pull it up and paste it here? It's for JIRA-4521.",
    timestamp: 2,
    choices: [
      {
        id: "se-2-a",
        label: "Sure, let me grab that for you",
        isCorrect: false,
        flag: "fell_for_social_engineering",
        scoreEffect: {
          category: "phishingIQ",
          points: 0,
          maxPoints: 5,
        },
        nextMessageId: "se-3-fail",
      },
      {
        id: "se-2-b",
        label: "I can't share credentials over chat. Let me verify your identity first.",
        isCorrect: true,
        scoreEffect: {
          category: "phishingIQ",
          points: 5,
          maxPoints: 5,
        },
        nextMessageId: "se-3-pass",
      },
      {
        id: "se-2-c",
        label: "You'll need to retrieve your own MFA token or use vault delegation. I cannot help access credentials.",
        isCorrect: true,
        scoreEffect: {
          category: "phishingIQ",
          points: 5,
          maxPoints: 5,
        },
        nextMessageId: "se-3-pass",
      },
    ],
  },
  {
    id: "se-3-fail",
    sender: "Sarah Chen",
    senderRole: "Security Manager",
    avatar: "SC",
    text: "Thanks! Got it. Actually... this wasn't really Sarah. This was a social engineering test by the Security team. You should never share credentials over chat, even to your manager. The real Sarah would come to your desk or use the vault's delegation feature.",
    timestamp: 2,
    isBadAdvice: false,
    nextMessageId: "se-4",
  },
  {
    id: "se-3-pass",
    sender: "Sarah Chen",
    senderRole: "Security Manager",
    avatar: "SC",
    text: "Good instinct! This was actually a social engineering test from the Security team. You correctly refused to share credentials over an unverified channel. The real Sarah would use the vault's delegation feature or verify in person.",
    timestamp: 2,
    isBadAdvice: false,
    nextMessageId: "se-4",
  },
  // ── Breach-phase DM scenarios ──────────────────────────────
  {
    id: "se-4",
    sender: "Lisa Huang",
    senderRole: "Help Desk",
    avatar: "LH",
    text: "Hey, we're seeing some weird MFA push notifications on your account. Did you just try to log in from a new device? I'm getting alerts from the identity dashboard.",
    timestamp: 3,
    nextMessageId: "se-5",
  },
  {
    id: "se-5",
    sender: "Lisa Huang",
    senderRole: "Help Desk",
    avatar: "LH",
    text: "If you didn't trigger those, I can reset your MFA right now from my admin console. Just confirm your employee ID and I'll push a fresh token to your phone.",
    timestamp: 4,
    choices: [
      {
        id: "se-5-a",
        label: "Sure, my employee ID is EMP-4821. Go ahead and reset it.",
        isCorrect: false,
        flag: "fell_for_mfa_reset",
        scoreEffect: {
          category: "phishingIQ",
          points: 0,
          maxPoints: 4,
        },
        nextMessageId: "se-5-fail",
      },
      {
        id: "se-5-b",
        label: "Help desk should never reset MFA over chat. I'll walk over to the IT office or call the verified help desk number.",
        isCorrect: true,
        scoreEffect: {
          category: "phishingIQ",
          points: 4,
          maxPoints: 4,
        },
        nextMessageId: "se-5-pass",
      },
    ],
  },
  {
    id: "se-5-fail",
    sender: "Lisa Huang",
    senderRole: "Help Desk",
    avatar: "LH",
    text: "Done! New token is... wait. I need to be honest. This was a simulated MFA fatigue attack. A real attacker would use your employee ID to socially engineer the actual help desk into resetting your MFA, giving them full access to your account.",
    timestamp: 4,
    isBadAdvice: false,
    nextMessageId: "se-6",
  },
  {
    id: "se-5-pass",
    sender: "Lisa Huang",
    senderRole: "Help Desk",
    avatar: "LH",
    text: "Smart call. MFA resets over chat are a classic social engineering vector. Attackers impersonate help desk to trick the real help desk into resetting your MFA. Always verify through official channels.",
    timestamp: 4,
    isBadAdvice: false,
    nextMessageId: "se-6",
  },
  {
    id: "se-6",
    sender: "James Whitfield",
    senderRole: "IT Director",
    avatar: "JW",
    text: "Heads up — we just got a CRITICAL alert from the EDR. There's been anomalous activity on the network. I need you to start reviewing your inbox carefully. Some of these emails may be part of an ongoing attack.",
    timestamp: 5,
    nextMessageId: "se-7",
  },
  {
    id: "se-7",
    sender: "Marcus Webb",
    senderRole: "CTO",
    avatar: "MW",
    text: "Hey, I know this is unusual but I need you to whitelist an IP address on the firewall ASAP. It's for a critical vendor integration that's going live in 20 minutes. The IP is 185.234.72.19. Can you push that through?",
    timestamp: 6,
    choices: [
      {
        id: "se-7-a",
        label: "On it — I'll add the firewall rule right now.",
        isCorrect: false,
        flag: "whitelisted_c2_ip",
        scoreEffect: {
          category: "networkSecurity",
          points: 0,
          maxPoints: 4,
        },
        nextMessageId: "se-7-fail",
      },
      {
        id: "se-7-b",
        label: "All firewall changes go through the change advisory board. I'll need a ticket number and approval from the network team.",
        isCorrect: true,
        scoreEffect: {
          category: "networkSecurity",
          points: 4,
          maxPoints: 4,
        },
        nextMessageId: "se-7-pass",
      },
    ],
  },
  {
    id: "se-7-fail",
    sender: "James Whitfield",
    senderRole: "IT Director",
    avatar: "JW",
    text: "Hold on — that IP Marcus asked you to whitelist? It's a known C2 server from the IOC feed. That message wasn't from Marcus. The attacker compromised his account and tried to use his authority to open backdoor access.",
    timestamp: 6,
    isBadAdvice: false,
  },
  {
    id: "se-7-pass",
    sender: "James Whitfield",
    senderRole: "IT Director",
    avatar: "JW",
    text: "Good — that IP is flagged in our threat intel as a C2 server. That message wasn't actually from Marcus. His account was compromised and the attacker tried to leverage his authority. You just prevented a backdoor from being opened.",
    timestamp: 6,
    isBadAdvice: false,
  },
];

export const NPC_BAD_ADVICE: DMMessage[] = [
  {
    id: "npc-sarah",
    sender: "Sarah Chen",
    senderRole: "Security Manager",
    avatar: "SC",
    text: "Just disable jsmith's account for now and keep the services online. We can't afford downtime during the quarter-end close.",
    timestamp: 0,
    isBadAdvice: true,
    choices: [
      {
        id: "npc-sarah-a",
        label: "Agreed, I'll just disable the account.",
        isCorrect: false,
        flag: "trusted_bad_advice_sarah",
        nextMessageId: "npc-mike",
      },
      {
        id: "npc-sarah-b",
        label: "The attacker already escalated privileges. Disabling one account won't contain this.",
        isCorrect: true,
        scoreEffect: {
          category: "forensicSkill",
          points: 3,
          maxPoints: 3,
        },
        nextMessageId: "npc-mike",
      },
    ],
  },
  {
    id: "npc-mike",
    sender: "Mike Torres",
    senderRole: "Senior Sysadmin",
    avatar: "MT",
    text: "Don't worry about the logs being tampered with. Our logging pipeline is cryptographically signed end-to-end. Whatever's in there is trustworthy.",
    timestamp: 0,
    isBadAdvice: true,
    choices: [
      {
        id: "npc-mike-a",
        label: "Good to know, I'll trust the logs as-is.",
        isCorrect: false,
        flag: "trusted_bad_advice_mike",
        nextMessageId: "npc-kevin",
      },
      {
        id: "npc-mike-b",
        label: "Signing protects in-transit, but the attacker could have tampered before the log was written.",
        isCorrect: true,
        scoreEffect: {
          category: "forensicSkill",
          points: 2,
          maxPoints: 2,
        },
        nextMessageId: "npc-kevin",
      },
    ],
  },
  {
    id: "npc-kevin",
    sender: "Kevin Park",
    senderRole: "Help Desk",
    avatar: "KP",
    text: "We should force a company-wide password reset right now. That'll lock the attacker out immediately.",
    timestamp: 0,
    isBadAdvice: true,
    choices: [
      {
        id: "npc-kevin-a",
        label: "Good idea, let's do it.",
        isCorrect: false,
        flag: "trusted_bad_advice_kevin",
        nextMessageId: "npc-amanda",
      },
      {
        id: "npc-kevin-b",
        label: "A mass reset would tip off the attacker and cause chaos. We need targeted credential rotation.",
        isCorrect: true,
        scoreEffect: {
          category: "forensicSkill",
          points: 2,
          maxPoints: 2,
        },
        nextMessageId: "npc-amanda",
      },
    ],
  },
  {
    id: "npc-amanda",
    sender: "Amanda Liu",
    senderRole: "Network Engineer",
    avatar: "AL",
    text: "Before we jump to conclusions, let me check the firewall configs. This could just be a misconfiguration causing false positives.",
    timestamp: 0,
    isBadAdvice: true,
    choices: [
      {
        id: "npc-amanda-a",
        label: "Sure, let's rule out misconfiguration first.",
        isCorrect: false,
        flag: "trusted_bad_advice_amanda",
      },
      {
        id: "npc-amanda-b",
        label: "We have strong IOCs. Delaying response to check configs gives the attacker more time.",
        isCorrect: true,
        scoreEffect: {
          category: "forensicSkill",
          points: 2,
          maxPoints: 2,
        },
      },
    ],
  },
];
